/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/pipelines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all pipelines
         * @description Returns a paginated list of pipelines
         */
        get: operations["listPipelines"];
        put?: never;
        /**
         * Create a new pipeline
         * @description Creates a new pipeline with the provided configuration
         */
        post: operations["createPipeline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipelines/{pipelineId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get pipeline by ID
         * @description Returns a single pipeline by its ID
         */
        get: operations["getPipeline"];
        put?: never;
        post?: never;
        /**
         * Delete pipeline
         * @description Deletes a pipeline by its ID
         */
        delete: operations["deletePipeline"];
        options?: never;
        head?: never;
        /**
         * Update pipeline
         * @description Updates an existing pipeline with partial data
         */
        patch: operations["updatePipeline"];
        trace?: never;
    };
    "/worker-pools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List worker pools
         * @description Returns a list of all worker pools
         */
        get: operations["listWorkerPools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/worker-pools/{poolId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get worker pool status
         * @description Returns the current status of a worker pool
         */
        get: operations["getWorkerPoolStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Pipeline: {
            /**
             * Format: uuid
             * @description Unique identifier for the pipeline
             */
            id: string;
            /** @description Name of the pipeline */
            name: string;
            /** @description Description of the pipeline */
            description?: string;
            /**
             * @description Current status of the pipeline
             * @enum {string}
             */
            status: "active" | "inactive" | "archived";
            /** @description Cron expression for scheduled execution */
            schedule?: string;
            /** @description Tags associated with the pipeline */
            tags?: string[];
            /**
             * Format: date-time
             * @description When the pipeline was created
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description When the pipeline was last updated
             */
            updatedAt?: string;
        };
        CreatePipelineRequest: {
            /** @description Name of the pipeline */
            name: string;
            /** @description Description of the pipeline */
            description?: string;
            /** @description Cron expression for scheduled execution */
            schedule?: string;
            /** @description Tags associated with the pipeline */
            tags?: string[];
        };
        UpdatePipelineRequest: {
            name?: string;
            description?: string;
            /** @enum {string} */
            status?: "active" | "inactive" | "archived";
            schedule?: string;
            tags?: string[];
        };
        WorkerPool: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** @enum {string} */
            poolType?: "Docker" | "Kubernetes" | "Native";
            providerName?: string;
            minSize?: number;
            maxSize?: number;
            defaultResources?: {
                /** @description CPU in millicores */
                cpu_m?: number;
                /** @description Memory in megabytes */
                memory_mb?: number;
                /** @description Number of GPUs */
                gpu?: number;
            };
            tags?: {
                [key: string]: string;
            };
        };
        WorkerPoolStatus: {
            name?: string;
            poolType?: string;
            totalCapacity?: number;
            availableCapacity?: number;
            activeWorkers?: number;
            pendingRequests?: number;
        };
        Error: {
            /** @description Error code */
            code: string;
            /** @description Error message */
            message: string;
            /** @description Additional error details */
            details?: Record<string, never>;
            /**
             * Format: date-time
             * @description When the error occurred
             */
            timestamp: string;
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "BAD_REQUEST",
                 *       "message": "Invalid request parameters",
                 *       "timestamp": "2025-11-30T12:00:00Z"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "UNAUTHORIZED",
                 *       "message": "Authentication required",
                 *       "timestamp": "2025-11-30T12:00:00Z"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "NOT_FOUND",
                 *       "message": "Resource not found",
                 *       "timestamp": "2025-11-30T12:00:00Z"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "CONFLICT",
                 *       "message": "Resource already exists",
                 *       "timestamp": "2025-11-30T12:00:00Z"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Internal server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "INTERNAL_ERROR",
                 *       "message": "An unexpected error occurred",
                 *       "timestamp": "2025-11-30T12:00:00Z"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listPipelines: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return */
                limit?: number;
                /** @description Number of items to skip */
                offset?: number;
                /** @description Filter by pipeline status */
                status?: "active" | "inactive" | "archived";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of pipelines */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["Pipeline"][];
                        total?: number;
                        hasMore?: boolean;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    createPipeline: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "web-app-build",
                 *       "description": "Build and deploy web application",
                 *       "schedule": "0 0 * * *",
                 *       "tags": [
                 *         "build",
                 *         "deploy"
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["CreatePipelineRequest"];
            };
        };
        responses: {
            /** @description Pipeline created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pipeline"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    getPipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the pipeline */
                pipelineId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pipeline details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pipeline"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deletePipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the pipeline */
                pipelineId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pipeline deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updatePipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the pipeline */
                pipelineId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePipelineRequest"];
            };
        };
        responses: {
            /** @description Pipeline updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pipeline"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listWorkerPools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of worker pools */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerPool"][];
                };
            };
        };
    };
    getWorkerPoolStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the worker pool */
                poolId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Worker pool status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerPoolStatus"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
