apiVersion: tests.testkube.io/v3
kind: TestSuite
metadata:
  name: hodei-smoke-tests
  namespace: testkube
  labels:
    app: hodei-pipelines
    suite: smoke
spec:
  description: "Smoke tests for Hodei Pipelines - Basic functionality verification"
  before:
    - namespace: testkube
      name: setup-test-environment
      description: "Setup test environment variables"
      commands:
        - kubectl create namespace hodei-test --dry-run=client -o yaml | kubectl apply -f -
  steps:
    - execute:
        - test: server-health-check
    - execute:
        - test: server-metrics-check
    - execute:
        - test: api-endpoints-validation
  after:
    - namespace: testkube
      name: cleanup-test-environment
      description: "Cleanup test environment"
      commands:
        - kubectl delete namespace hodei-test --ignore-not-found=true
  tags:
    - smoke
    - critical
